// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	admin_users "github.com/colinrs/shopjoy/admin/internal/handler/admin_users"
	auth "github.com/colinrs/shopjoy/admin/internal/handler/auth"
	brands "github.com/colinrs/shopjoy/admin/internal/handler/brands"
	categories "github.com/colinrs/shopjoy/admin/internal/handler/categories"
	coupons "github.com/colinrs/shopjoy/admin/internal/handler/coupons"
	fulfillment_orders "github.com/colinrs/shopjoy/admin/internal/handler/fulfillment_orders"
	inventory "github.com/colinrs/shopjoy/admin/internal/handler/inventory"
	markets "github.com/colinrs/shopjoy/admin/internal/handler/markets"
	payments "github.com/colinrs/shopjoy/admin/internal/handler/payments"
	product_markets "github.com/colinrs/shopjoy/admin/internal/handler/product_markets"
	products "github.com/colinrs/shopjoy/admin/internal/handler/products"
	promotions "github.com/colinrs/shopjoy/admin/internal/handler/promotions"
	refunds "github.com/colinrs/shopjoy/admin/internal/handler/refunds"
	reviews "github.com/colinrs/shopjoy/admin/internal/handler/reviews"
	shipments "github.com/colinrs/shopjoy/admin/internal/handler/shipments"
	user_coupons "github.com/colinrs/shopjoy/admin/internal/handler/user_coupons"
	users "github.com/colinrs/shopjoy/admin/internal/handler/users"
	warehouses "github.com/colinrs/shopjoy/admin/internal/handler/warehouses"
	webhooks "github.com/colinrs/shopjoy/admin/internal/handler/webhooks"
	"github.com/colinrs/shopjoy/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 获取管理员列表
					Method:  http.MethodGet,
					Path:    "/api/v1/admin-users",
					Handler: admin_users.ListAdminUsersHandler(serverCtx),
				},
				{
					// 禁用管理员
					Method:  http.MethodPost,
					Path:    "/api/v1/admin-users/:id/disable",
					Handler: admin_users.DisableAdminUserHandler(serverCtx),
				},
				{
					// 启用管理员
					Method:  http.MethodPost,
					Path:    "/api/v1/admin-users/:id/enable",
					Handler: admin_users.EnableAdminUserHandler(serverCtx),
				},
				{
					// 修改管理员密码
					Method:  http.MethodPut,
					Path:    "/api/v1/admin-users/password",
					Handler: admin_users.ChangeAdminPasswordHandler(serverCtx),
				},
				{
					// 更新管理员资料
					Method:  http.MethodPut,
					Path:    "/api/v1/admin-users/profile",
					Handler: admin_users.UpdateAdminProfileHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 管理员登录
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/login",
				Handler: auth.AdminLoginHandler(serverCtx),
			},
			{
				// 注册租户管理员
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/register",
				Handler: auth.RegisterTenantAdminHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建品牌
					Method:  http.MethodPost,
					Path:    "/api/v1/brands",
					Handler: brands.CreateBrandHandler(serverCtx),
				},
				{
					// 获取品牌列表
					Method:  http.MethodGet,
					Path:    "/api/v1/brands",
					Handler: brands.ListBrandsHandler(serverCtx),
				},
				{
					// 更新品牌
					Method:  http.MethodPut,
					Path:    "/api/v1/brands/:id",
					Handler: brands.UpdateBrandHandler(serverCtx),
				},
				{
					// 获取品牌详情
					Method:  http.MethodGet,
					Path:    "/api/v1/brands/:id",
					Handler: brands.GetBrandHandler(serverCtx),
				},
				{
					// 删除品牌
					Method:  http.MethodDelete,
					Path:    "/api/v1/brands/:id",
					Handler: brands.DeleteBrandHandler(serverCtx),
				},
				{
					// 设置品牌市场可见性
					Method:  http.MethodPut,
					Path:    "/api/v1/brands/:id/market-visibility",
					Handler: brands.SetBrandMarketVisibilityHandler(serverCtx),
				},
				{
					// 获取品牌市场可见性
					Method:  http.MethodGet,
					Path:    "/api/v1/brands/:id/market-visibility",
					Handler: brands.GetBrandMarketVisibilityHandler(serverCtx),
				},
				{
					// 获取品牌下商品数量
					Method:  http.MethodGet,
					Path:    "/api/v1/brands/:id/product-count",
					Handler: brands.GetBrandProductCountHandler(serverCtx),
				},
				{
					// 更新品牌状态
					Method:  http.MethodPut,
					Path:    "/api/v1/brands/:id/status",
					Handler: brands.UpdateBrandStatusHandler(serverCtx),
				},
				{
					// 切换品牌专区
					Method:  http.MethodPut,
					Path:    "/api/v1/brands/:id/toggle-page",
					Handler: brands.ToggleBrandPageHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建分类
					Method:  http.MethodPost,
					Path:    "/api/v1/categories",
					Handler: categories.CreateCategoryHandler(serverCtx),
				},
				{
					// 获取分类列表
					Method:  http.MethodGet,
					Path:    "/api/v1/categories",
					Handler: categories.ListCategoriesHandler(serverCtx),
				},
				{
					// 更新分类
					Method:  http.MethodPut,
					Path:    "/api/v1/categories/:id",
					Handler: categories.UpdateCategoryHandler(serverCtx),
				},
				{
					// 获取分类详情
					Method:  http.MethodGet,
					Path:    "/api/v1/categories/:id",
					Handler: categories.GetCategoryHandler(serverCtx),
				},
				{
					// 删除分类
					Method:  http.MethodDelete,
					Path:    "/api/v1/categories/:id",
					Handler: categories.DeleteCategoryHandler(serverCtx),
				},
				{
					// 设置分类市场可见性
					Method:  http.MethodPut,
					Path:    "/api/v1/categories/:id/market-visibility",
					Handler: categories.SetCategoryMarketVisibilityHandler(serverCtx),
				},
				{
					// 获取分类市场可见性
					Method:  http.MethodGet,
					Path:    "/api/v1/categories/:id/market-visibility",
					Handler: categories.GetCategoryMarketVisibilityHandler(serverCtx),
				},
				{
					// 移动分类
					Method:  http.MethodPut,
					Path:    "/api/v1/categories/:id/move",
					Handler: categories.MoveCategoryHandler(serverCtx),
				},
				{
					// 获取分类下商品数量
					Method:  http.MethodGet,
					Path:    "/api/v1/categories/:id/product-count",
					Handler: categories.GetCategoryProductCountHandler(serverCtx),
				},
				{
					// 更新分类状态
					Method:  http.MethodPut,
					Path:    "/api/v1/categories/:id/status",
					Handler: categories.UpdateCategoryStatusHandler(serverCtx),
				},
				{
					// 更新分类排序
					Method:  http.MethodPut,
					Path:    "/api/v1/categories/sort",
					Handler: categories.UpdateCategorySortHandler(serverCtx),
				},
				{
					// 获取分类树
					Method:  http.MethodGet,
					Path:    "/api/v1/categories/tree",
					Handler: categories.GetCategoryTreeHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建优惠券
					Method:  http.MethodPost,
					Path:    "/api/v1/coupons",
					Handler: coupons.CreateCouponHandler(serverCtx),
				},
				{
					// 获取优惠券列表
					Method:  http.MethodGet,
					Path:    "/api/v1/coupons",
					Handler: coupons.ListCouponsHandler(serverCtx),
				},
				{
					// 更新优惠券
					Method:  http.MethodPut,
					Path:    "/api/v1/coupons/:id",
					Handler: coupons.UpdateCouponHandler(serverCtx),
				},
				{
					// 获取优惠券详情
					Method:  http.MethodGet,
					Path:    "/api/v1/coupons/:id",
					Handler: coupons.GetCouponHandler(serverCtx),
				},
				{
					// 删除优惠券
					Method:  http.MethodDelete,
					Path:    "/api/v1/coupons/:id",
					Handler: coupons.DeleteCouponHandler(serverCtx),
				},
				{
					// 获取优惠券使用记录
					Method:  http.MethodGet,
					Path:    "/api/v1/coupons/:id/usage",
					Handler: coupons.GetCouponUsageHandler(serverCtx),
				},
				{
					// 批量生成优惠券码
					Method:  http.MethodPost,
					Path:    "/api/v1/coupons/generate",
					Handler: coupons.GenerateCouponCodesHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 订单列表（含履约状态筛选）
					Method:  http.MethodGet,
					Path:    "/api/v1/orders",
					Handler: fulfillment_orders.ListFulfillmentOrdersHandler(serverCtx),
				},
				{
					// 订单详情（含履约信息）
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id",
					Handler: fulfillment_orders.GetOrderFulfillmentHandler(serverCtx),
				},
				{
					// 订单改价
					Method:  http.MethodPut,
					Path:    "/api/v1/orders/:id/adjust-price",
					Handler: fulfillment_orders.AdjustOrderPriceHandler(serverCtx),
				},
				{
					// 更新订单备注
					Method:  http.MethodPut,
					Path:    "/api/v1/orders/:id/remark",
					Handler: fulfillment_orders.UpdateOrderRemarkHandler(serverCtx),
				},
				{
					// 订单发货（创建发货单）
					Method:  http.MethodPut,
					Path:    "/api/v1/orders/:id/ship",
					Handler: fulfillment_orders.ShipOrderHandler(serverCtx),
				},
				{
					// 导出订单
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/export",
					Handler: fulfillment_orders.ExportOrdersHandler(serverCtx),
				},
				{
					// 履约摘要统计
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/fulfillment-summary",
					Handler: fulfillment_orders.GetFulfillmentSummaryHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 调整库存
					Method:  http.MethodPost,
					Path:    "/api/v1/inventory/adjust",
					Handler: inventory.AdjustStockHandler(serverCtx),
				},
				{
					// 获取库存日志
					Method:  http.MethodGet,
					Path:    "/api/v1/inventory/logs",
					Handler: inventory.GetInventoryLogsHandler(serverCtx),
				},
				{
					// 获取低库存SKU列表
					Method:  http.MethodGet,
					Path:    "/api/v1/inventory/low-stock",
					Handler: inventory.GetLowStockSKUsHandler(serverCtx),
				},
				{
					// 批量更新安全库存
					Method:  http.MethodPut,
					Path:    "/api/v1/inventory/safety-stock",
					Handler: inventory.BatchUpdateSafetyStockHandler(serverCtx),
				},
				{
					// 获取SKU库存
					Method:  http.MethodGet,
					Path:    "/api/v1/inventory/sku/:sku_code",
					Handler: inventory.GetSKUInventoryHandler(serverCtx),
				},
				{
					// 更新SKU库存
					Method:  http.MethodPut,
					Path:    "/api/v1/inventory/stock",
					Handler: inventory.UpdateSKUStockHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建市场
					Method:  http.MethodPost,
					Path:    "/api/v1/markets",
					Handler: markets.CreateMarketHandler(serverCtx),
				},
				{
					// 获取市场列表
					Method:  http.MethodGet,
					Path:    "/api/v1/markets",
					Handler: markets.ListMarketsHandler(serverCtx),
				},
				{
					// 更新市场
					Method:  http.MethodPut,
					Path:    "/api/v1/markets/:id",
					Handler: markets.UpdateMarketHandler(serverCtx),
				},
				{
					// 获取市场详情
					Method:  http.MethodGet,
					Path:    "/api/v1/markets/:id",
					Handler: markets.GetMarketHandler(serverCtx),
				},
				{
					// 删除市场
					Method:  http.MethodDelete,
					Path:    "/api/v1/markets/:id",
					Handler: markets.DeleteMarketHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 订单支付信息
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:id/payment",
					Handler: payments.GetOrderPaymentHandler(serverCtx),
				},
				{
					// 发起退款
					Method:  http.MethodPost,
					Path:    "/api/v1/orders/:id/refund",
					Handler: payments.InitiateRefundHandler(serverCtx),
				},
				{
					// 支付统计
					Method:  http.MethodGet,
					Path:    "/api/v1/payments/stats",
					Handler: payments.GetPaymentStatsHandler(serverCtx),
				},
				{
					// 支付流水列表
					Method:  http.MethodGet,
					Path:    "/api/v1/payments/transactions",
					Handler: payments.ListTransactionsHandler(serverCtx),
				},
				{
					// 支付流水详情
					Method:  http.MethodGet,
					Path:    "/api/v1/payments/transactions/:id",
					Handler: payments.GetTransactionHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 获取商品市场配置列表
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:id/markets",
					Handler: product_markets.ListProductMarketsHandler(serverCtx),
				},
				{
					// 更新商品市场配置
					Method:  http.MethodPut,
					Path:    "/api/v1/products/:id/markets/:market_id",
					Handler: product_markets.UpdateProductMarketHandler(serverCtx),
				},
				{
					// 从市场移除商品
					Method:  http.MethodDelete,
					Path:    "/api/v1/products/:id/markets/:market_id",
					Handler: product_markets.RemoveFromMarketHandler(serverCtx),
				},
				{
					// 推送商品到市场
					Method:  http.MethodPost,
					Path:    "/api/v1/products/:id/push-to-market",
					Handler: product_markets.PushToMarketHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建商品本地化
					Method:  http.MethodPost,
					Path:    "/api/v1/product-localizations",
					Handler: products.CreateProductLocalizationHandler(serverCtx),
				},
				{
					// 更新商品本地化
					Method:  http.MethodPut,
					Path:    "/api/v1/product-localizations/:id",
					Handler: products.UpdateProductLocalizationHandler(serverCtx),
				},
				{
					// 获取商品本地化详情
					Method:  http.MethodGet,
					Path:    "/api/v1/product-localizations/:id",
					Handler: products.GetProductLocalizationHandler(serverCtx),
				},
				{
					// 删除商品本地化
					Method:  http.MethodDelete,
					Path:    "/api/v1/product-localizations/:id",
					Handler: products.DeleteProductLocalizationHandler(serverCtx),
				},
				{
					// 创建商品
					Method:  http.MethodPost,
					Path:    "/api/v1/products",
					Handler: products.CreateProductHandler(serverCtx),
				},
				{
					// 获取商品列表
					Method:  http.MethodGet,
					Path:    "/api/v1/products",
					Handler: products.ListProductHandler(serverCtx),
				},
				{
					// 更新商品
					Method:  http.MethodPut,
					Path:    "/api/v1/products/:id",
					Handler: products.UpdateProductHandler(serverCtx),
				},
				{
					// 获取商品详情
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:id",
					Handler: products.GetProductHandler(serverCtx),
				},
				{
					// 下架商品
					Method:  http.MethodPost,
					Path:    "/api/v1/products/:id/off-sale",
					Handler: products.TakeOffSaleHandler(serverCtx),
				},
				{
					// 上架商品
					Method:  http.MethodPost,
					Path:    "/api/v1/products/:id/on-sale",
					Handler: products.PutOnSaleHandler(serverCtx),
				},
				{
					// 更新库存
					Method:  http.MethodPut,
					Path:    "/api/v1/products/:id/stock",
					Handler: products.UpdateStockHandler(serverCtx),
				},
				{
					// 获取商品本地化列表
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:product_id/localizations",
					Handler: products.ListProductLocalizationsByProductHandler(serverCtx),
				},
				{
					// 获取商品SKU列表
					Method:  http.MethodGet,
					Path:    "/api/v1/products/:product_id/skus",
					Handler: products.ListSKUsByProductHandler(serverCtx),
				},
				{
					// 创建SKU变体
					Method:  http.MethodPost,
					Path:    "/api/v1/skus",
					Handler: products.CreateSKUHandler(serverCtx),
				},
				{
					// 更新SKU变体
					Method:  http.MethodPut,
					Path:    "/api/v1/skus/:id",
					Handler: products.UpdateSKUHandler(serverCtx),
				},
				{
					// 获取SKU详情
					Method:  http.MethodGet,
					Path:    "/api/v1/skus/:id",
					Handler: products.GetSKUHandler(serverCtx),
				},
				{
					// 删除SKU变体
					Method:  http.MethodDelete,
					Path:    "/api/v1/skus/:id",
					Handler: products.DeleteSKUHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 更新促销规则
					Method:  http.MethodPut,
					Path:    "/api/v1/promotion-rules/:id",
					Handler: promotions.UpdatePromotionRuleHandler(serverCtx),
				},
				{
					// 删除促销规则
					Method:  http.MethodDelete,
					Path:    "/api/v1/promotion-rules/:id",
					Handler: promotions.DeletePromotionRuleHandler(serverCtx),
				},
				{
					// 创建促销活动
					Method:  http.MethodPost,
					Path:    "/api/v1/promotions",
					Handler: promotions.CreatePromotionHandler(serverCtx),
				},
				{
					// 获取促销活动列表
					Method:  http.MethodGet,
					Path:    "/api/v1/promotions",
					Handler: promotions.ListPromotionsHandler(serverCtx),
				},
				{
					// 更新促销活动
					Method:  http.MethodPut,
					Path:    "/api/v1/promotions/:id",
					Handler: promotions.UpdatePromotionHandler(serverCtx),
				},
				{
					// 获取促销活动详情
					Method:  http.MethodGet,
					Path:    "/api/v1/promotions/:id",
					Handler: promotions.GetPromotionHandler(serverCtx),
				},
				{
					// 删除促销活动
					Method:  http.MethodDelete,
					Path:    "/api/v1/promotions/:id",
					Handler: promotions.DeletePromotionHandler(serverCtx),
				},
				{
					// 激活促销活动
					Method:  http.MethodPost,
					Path:    "/api/v1/promotions/:id/activate",
					Handler: promotions.ActivatePromotionHandler(serverCtx),
				},
				{
					// 停用促销活动
					Method:  http.MethodPost,
					Path:    "/api/v1/promotions/:id/deactivate",
					Handler: promotions.DeactivatePromotionHandler(serverCtx),
				},
				{
					// 获取促销规则列表
					Method:  http.MethodGet,
					Path:    "/api/v1/promotions/:id/rules",
					Handler: promotions.GetPromotionRulesHandler(serverCtx),
				},
				{
					// 添加促销规则
					Method:  http.MethodPost,
					Path:    "/api/v1/promotions/:id/rules",
					Handler: promotions.CreatePromotionRulesHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 退款原因列表
					Method:  http.MethodGet,
					Path:    "/api/v1/refund-reasons",
					Handler: refunds.ListRefundReasonsHandler(serverCtx),
				},
				{
					// 退款列表
					Method:  http.MethodGet,
					Path:    "/api/v1/refunds",
					Handler: refunds.ListRefundsHandler(serverCtx),
				},
				{
					// 退款详情
					Method:  http.MethodGet,
					Path:    "/api/v1/refunds/:id",
					Handler: refunds.GetRefundHandler(serverCtx),
				},
				{
					// 批准退款
					Method:  http.MethodPut,
					Path:    "/api/v1/refunds/:id/approve",
					Handler: refunds.ApproveRefundHandler(serverCtx),
				},
				{
					// 拒绝退款
					Method:  http.MethodPut,
					Path:    "/api/v1/refunds/:id/reject",
					Handler: refunds.RejectRefundHandler(serverCtx),
				},
				{
					// 退款统计
					Method:  http.MethodGet,
					Path:    "/api/v1/refunds/statistics",
					Handler: refunds.GetRefundStatisticsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 获取评价列表
					Method:  http.MethodGet,
					Path:    "/api/v1/reviews",
					Handler: reviews.ListReviewsHandler(serverCtx),
				},
				{
					// 获取评价详情
					Method:  http.MethodGet,
					Path:    "/api/v1/reviews/:id",
					Handler: reviews.GetReviewHandler(serverCtx),
				},
				{
					// 删除评价
					Method:  http.MethodDelete,
					Path:    "/api/v1/reviews/:id",
					Handler: reviews.DeleteReviewHandler(serverCtx),
				},
				{
					// 批准评价
					Method:  http.MethodPut,
					Path:    "/api/v1/reviews/:id/approve",
					Handler: reviews.ApproveReviewHandler(serverCtx),
				},
				{
					// 设置精选
					Method:  http.MethodPut,
					Path:    "/api/v1/reviews/:id/featured",
					Handler: reviews.ToggleFeaturedHandler(serverCtx),
				},
				{
					// 隐藏评价
					Method:  http.MethodPut,
					Path:    "/api/v1/reviews/:id/hide",
					Handler: reviews.HideReviewHandler(serverCtx),
				},
				{
					// 创建回复
					Method:  http.MethodPost,
					Path:    "/api/v1/reviews/:id/reply",
					Handler: reviews.CreateReplyHandler(serverCtx),
				},
				{
					// 更新回复
					Method:  http.MethodPut,
					Path:    "/api/v1/reviews/:id/reply",
					Handler: reviews.UpdateReplyHandler(serverCtx),
				},
				{
					// 删除回复
					Method:  http.MethodDelete,
					Path:    "/api/v1/reviews/:id/reply",
					Handler: reviews.DeleteReplyHandler(serverCtx),
				},
				{
					// 显示评价
					Method:  http.MethodPut,
					Path:    "/api/v1/reviews/:id/show",
					Handler: reviews.ShowReviewHandler(serverCtx),
				},
				{
					// 批量批准
					Method:  http.MethodPost,
					Path:    "/api/v1/reviews/batch-approve",
					Handler: reviews.BatchApproveHandler(serverCtx),
				},
				{
					// 批量隐藏
					Method:  http.MethodPost,
					Path:    "/api/v1/reviews/batch-hide",
					Handler: reviews.BatchHideHandler(serverCtx),
				},
				{
					// 获取商品评价统计
					Method:  http.MethodGet,
					Path:    "/api/v1/reviews/product/:product_id/stats",
					Handler: reviews.GetProductStatsHandler(serverCtx),
				},
				{
					// 获取评价统计
					Method:  http.MethodGet,
					Path:    "/api/v1/reviews/stats",
					Handler: reviews.GetReviewStatsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 物流公司列表
					Method:  http.MethodGet,
					Path:    "/api/v1/carriers",
					Handler: shipments.ListCarriersHandler(serverCtx),
				},
				{
					// 获取订单的发货单列表
					Method:  http.MethodGet,
					Path:    "/api/v1/orders/:order_id/shipments",
					Handler: shipments.GetOrderShipmentsHandler(serverCtx),
				},
				{
					// 创建发货单
					Method:  http.MethodPost,
					Path:    "/api/v1/shipments",
					Handler: shipments.CreateShipmentHandler(serverCtx),
				},
				{
					// 发货单列表
					Method:  http.MethodGet,
					Path:    "/api/v1/shipments",
					Handler: shipments.ListShipmentsHandler(serverCtx),
				},
				{
					// 发货单详情
					Method:  http.MethodGet,
					Path:    "/api/v1/shipments/:id",
					Handler: shipments.GetShipmentHandler(serverCtx),
				},
				{
					// 更新发货单
					Method:  http.MethodPut,
					Path:    "/api/v1/shipments/:id",
					Handler: shipments.UpdateShipmentHandler(serverCtx),
				},
				{
					// 更新发货单状态
					Method:  http.MethodPut,
					Path:    "/api/v1/shipments/:id/status",
					Handler: shipments.UpdateShipmentStatusHandler(serverCtx),
				},
				{
					// 批量创建发货单
					Method:  http.MethodPost,
					Path:    "/api/v1/shipments/batch",
					Handler: shipments.BatchCreateShipmentsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 发放优惠券给用户
					Method:  http.MethodPost,
					Path:    "/api/v1/user-coupons",
					Handler: user_coupons.IssueUserCouponHandler(serverCtx),
				},
				{
					// 获取用户优惠券列表
					Method:  http.MethodGet,
					Path:    "/api/v1/user-coupons",
					Handler: user_coupons.ListUserCouponsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 获取用户列表
					Method:  http.MethodGet,
					Path:    "/api/v1/users",
					Handler: users.ListUsersHandler(serverCtx),
				},
				{
					// 获取用户详情
					Method:  http.MethodGet,
					Path:    "/api/v1/users/:id",
					Handler: users.GetUserHandler(serverCtx),
				},
				{
					// 更新用户信息
					Method:  http.MethodPut,
					Path:    "/api/v1/users/:id",
					Handler: users.UpdateUserHandler(serverCtx),
				},
				{
					// 删除用户
					Method:  http.MethodDelete,
					Path:    "/api/v1/users/:id",
					Handler: users.DeleteUserHandler(serverCtx),
				},
				{
					// 启用用户
					Method:  http.MethodPost,
					Path:    "/api/v1/users/:id/activate",
					Handler: users.ActivateUserHandler(serverCtx),
				},
				{
					// 获取用户地址列表
					Method:  http.MethodGet,
					Path:    "/api/v1/users/:id/addresses",
					Handler: users.GetUserAddressesHandler(serverCtx),
				},
				{
					// 获取用户详情（含聚合数据）
					Method:  http.MethodGet,
					Path:    "/api/v1/users/:id/detail",
					Handler: users.GetUserDetailHandler(serverCtx),
				},
				{
					// 重置用户密码
					Method:  http.MethodPost,
					Path:    "/api/v1/users/:id/reset-password",
					Handler: users.ResetPasswordHandler(serverCtx),
				},
				{
					// 禁用用户
					Method:  http.MethodPost,
					Path:    "/api/v1/users/:id/suspend",
					Handler: users.SuspendUserHandler(serverCtx),
				},
				{
					// 冻结用户（带原因）
					Method:  http.MethodPost,
					Path:    "/api/v1/users/:id/suspend-reason",
					Handler: users.SuspendUserWithReasonHandler(serverCtx),
				},
				{
					// 获取增强版用户列表
					Method:  http.MethodGet,
					Path:    "/api/v1/users/enhanced",
					Handler: users.ListUsersEnhancedHandler(serverCtx),
				},
				{
					// 导出用户列表
					Method:  http.MethodGet,
					Path:    "/api/v1/users/export",
					Handler: users.ExportUsersHandler(serverCtx),
				},
				{
					// 获取用户统计
					Method:  http.MethodGet,
					Path:    "/api/v1/users/stats",
					Handler: users.GetUserStatsHandler(serverCtx),
				},
				{
					// 获取用户统计（增强版）
					Method:  http.MethodGet,
					Path:    "/api/v1/users/stats/enhanced",
					Handler: users.GetUserStatsEnhancedHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建仓库
					Method:  http.MethodPost,
					Path:    "/api/v1/warehouses",
					Handler: warehouses.CreateWarehouseHandler(serverCtx),
				},
				{
					// 获取仓库列表
					Method:  http.MethodGet,
					Path:    "/api/v1/warehouses",
					Handler: warehouses.ListWarehousesHandler(serverCtx),
				},
				{
					// 更新仓库
					Method:  http.MethodPut,
					Path:    "/api/v1/warehouses/:id",
					Handler: warehouses.UpdateWarehouseHandler(serverCtx),
				},
				{
					// 获取仓库详情
					Method:  http.MethodGet,
					Path:    "/api/v1/warehouses/:id",
					Handler: warehouses.GetWarehouseHandler(serverCtx),
				},
				{
					// 删除仓库
					Method:  http.MethodDelete,
					Path:    "/api/v1/warehouses/:id",
					Handler: warehouses.DeleteWarehouseHandler(serverCtx),
				},
				{
					// 设置默认仓库
					Method:  http.MethodPut,
					Path:    "/api/v1/warehouses/:id/default",
					Handler: warehouses.SetDefaultWarehouseHandler(serverCtx),
				},
				{
					// 更新仓库状态
					Method:  http.MethodPut,
					Path:    "/api/v1/warehouses/:id/status",
					Handler: warehouses.UpdateWarehouseStatusHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Stripe Webhook回调
				Method:  http.MethodPost,
				Path:    "/api/v1/webhooks/stripe",
				Handler: webhooks.StripeWebhookHandler(serverCtx),
			},
		},
	)
}
