// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	admin_users "github.com/colinrs/shopjoy/admin/internal/handler/admin_users"
	auth "github.com/colinrs/shopjoy/admin/internal/handler/auth"
	products "github.com/colinrs/shopjoy/admin/internal/handler/products"
	users "github.com/colinrs/shopjoy/admin/internal/handler/users"
	"github.com/colinrs/shopjoy/admin/internal/middleware"
	"github.com/colinrs/shopjoy/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// Auth middleware for protected routes
	authMiddleware := middleware.NewAuthMiddleware(serverCtx.Config.JWT.Secret)

	// Admin users routes (require auth)
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取管理员列表
				Method:  http.MethodGet,
				Path:    "/api/v1/admin-users",
				Handler: authMiddleware.Handle(admin_users.ListAdminUsersHandler(serverCtx)),
			},
			{
				// 禁用管理员
				Method:  http.MethodPost,
				Path:    "/api/v1/admin-users/:id/disable",
				Handler: authMiddleware.Handle(admin_users.DisableAdminUserHandler(serverCtx)),
			},
			{
				// 启用管理员
				Method:  http.MethodPost,
				Path:    "/api/v1/admin-users/:id/enable",
				Handler: authMiddleware.Handle(admin_users.EnableAdminUserHandler(serverCtx)),
			},
			{
				// 修改管理员密码
				Method:  http.MethodPut,
				Path:    "/api/v1/admin-users/password",
				Handler: authMiddleware.Handle(admin_users.ChangeAdminPasswordHandler(serverCtx)),
			},
			{
				// 更新管理员资料
				Method:  http.MethodPut,
				Path:    "/api/v1/admin-users/profile",
				Handler: authMiddleware.Handle(admin_users.UpdateAdminProfileHandler(serverCtx)),
			},
		},
	)

	// Auth routes (no auth required)
	server.AddRoutes(
		[]rest.Route{
			{
				// 管理员登录
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/login",
				Handler: auth.AdminLoginHandler(serverCtx),
			},
			{
				// 注册租户管理员
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/register",
				Handler: auth.RegisterTenantAdminHandler(serverCtx),
			},
		},
	)

	// Product routes (require auth)
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建商品
				Method:  http.MethodPost,
				Path:    "/api/v1/products",
				Handler: authMiddleware.Handle(products.CreateProductHandler(serverCtx)),
			},
			{
				// 获取商品列表
				Method:  http.MethodGet,
				Path:    "/api/v1/products",
				Handler: authMiddleware.Handle(products.ListProductHandler(serverCtx)),
			},
			{
				// 更新商品
				Method:  http.MethodPut,
				Path:    "/api/v1/products/:id",
				Handler: authMiddleware.Handle(products.UpdateProductHandler(serverCtx)),
			},
			{
				// 获取商品详情
				Method:  http.MethodGet,
				Path:    "/api/v1/products/:id",
				Handler: authMiddleware.Handle(products.GetProductHandler(serverCtx)),
			},
			{
				// 下架商品
				Method:  http.MethodPost,
				Path:    "/api/v1/products/:id/off-sale",
				Handler: authMiddleware.Handle(products.TakeOffSaleHandler(serverCtx)),
			},
			{
				// 上架商品
				Method:  http.MethodPost,
				Path:    "/api/v1/products/:id/on-sale",
				Handler: authMiddleware.Handle(products.PutOnSaleHandler(serverCtx)),
			},
			{
				// 更新库存
				Method:  http.MethodPut,
				Path:    "/api/v1/products/:id/stock",
				Handler: authMiddleware.Handle(products.UpdateStockHandler(serverCtx)),
			},
		},
	)

	// User routes (require auth)
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户列表
				Method:  http.MethodGet,
				Path:    "/api/v1/users",
				Handler: authMiddleware.Handle(users.ListUsersHandler(serverCtx)),
			},
			{
				// 获取用户详情
				Method:  http.MethodGet,
				Path:    "/api/v1/users/:id",
				Handler: authMiddleware.Handle(users.GetUserHandler(serverCtx)),
			},
			{
				// 更新用户信息
				Method:  http.MethodPut,
				Path:    "/api/v1/users/:id",
				Handler: authMiddleware.Handle(users.UpdateUserHandler(serverCtx)),
			},
		},
	)
}
