// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/colinrs/shopjoy/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: AdminHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建商品
				Method:  http.MethodPost,
				Path:    "/api/v1/products",
				Handler: CreateProductHandler(serverCtx),
			},
			{
				// 获取商品列表
				Method:  http.MethodGet,
				Path:    "/api/v1/products",
				Handler: ListProductHandler(serverCtx),
			},
			{
				// 更新商品
				Method:  http.MethodPut,
				Path:    "/api/v1/products/:id",
				Handler: UpdateProductHandler(serverCtx),
			},
			{
				// 获取商品详情
				Method:  http.MethodGet,
				Path:    "/api/v1/products/:id",
				Handler: GetProductHandler(serverCtx),
			},
			{
				// 下架商品
				Method:  http.MethodPost,
				Path:    "/api/v1/products/:id/off-sale",
				Handler: TakeOffSaleHandler(serverCtx),
			},
			{
				// 上架商品
				Method:  http.MethodPost,
				Path:    "/api/v1/products/:id/on-sale",
				Handler: PutOnSaleHandler(serverCtx),
			},
			{
				// 更新库存
				Method:  http.MethodPut,
				Path:    "/api/v1/products/:id/stock",
				Handler: UpdateStockHandler(serverCtx),
			},
		},
	)
}
