// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChangePasswordRequest struct {
	OldPassword     string `json:"old_password"`
	NewPassword     string `json:"new_password" validate:"min=6"`
	ConfirmPassword string `json:"confirm_password"`
}

type CreateProductReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Price       int64  `json:"price"`
	Currency    string `json:"currency,optional"`
	CostPrice   int64  `json:"cost_price,optional"`
	CategoryID  int64  `json:"category_id"`
}

type CreateProductResp struct {
	ID int64 `json:"id"`
}

type GetProductReq struct {
	ID int64 `path:"id"`
}

type GetUserRequest struct {
	ID int64 `path:"id"`
}

type GetUserResponse struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Status    int    `json:"status"`
	CreatedAt string `json:"created_at"`
}

type ListProductReq struct {
	Name       string `form:"name,optional"`
	CategoryID int64  `form:"category_id,optional"`
	Status     string `form:"status,optional"`
	MinPrice   int64  `form:"min_price,optional"`
	MaxPrice   int64  `form:"max_price,optional"`
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"page_size,default=20"`
}

type ListProductResp struct {
	List     []*ProductDetailResp `json:"list"`
	Total    int64                `json:"total"`
	Page     int                  `json:"page"`
	PageSize int                  `json:"page_size"`
}

type ListUsersRequest struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Name     string `form:"name,optional"`
	Email    string `form:"email,optional"`
}

type ListUsersResponse struct {
	List     []*GetUserResponse `json:"list"`
	Total    int64              `json:"total"`
	Page     int                `json:"page"`
	PageSize int                `json:"page_size"`
}

type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
}

type LoginResponse struct {
	AccessToken  string   `json:"access_token"`
	RefreshToken string   `json:"refresh_token"`
	ExpiresIn    int64    `json:"expires_in"`
	User         UserInfo `json:"user"`
}

type ProductDetailResp struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
	Currency    string `json:"currency"`
	CostPrice   int64  `json:"cost_price"`
	Stock       int    `json:"stock"`
	Status      string `json:"status"`
	CategoryID  int64  `json:"category_id"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type PutOnSaleReq struct {
	ID int64 `path:"id"`
}

type RegisterRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Phone    string `json:"phone,optional"`
	Password string `json:"password" validate:"required,min=6"`
	Name     string `json:"name" validate:"required"`
}

type RegisterResponse struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type TakeOffSaleReq struct {
	ID int64 `path:"id"`
}

type UpdateProductReq struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Price       int64  `json:"price"`
	Currency    string `json:"currency,optional"`
	CategoryID  int64  `json:"category_id"`
}

type UpdateStockReq struct {
	ID       int64 `path:"id"`
	Quantity int   `json:"quantity"`
}

type UpdateUserRequest struct {
	ID     int64  `path:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar,optional"`
}

type UserInfo struct {
	ID     int64  `json:"id"`
	Email  string `json:"email"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}
