// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdjustStockReq struct {
	SKUCode     string `json:"sku_code"`
	WarehouseID int64  `json:"warehouse_id"`
	Quantity    int    `json:"quantity"` // positive = increase, negative = decrease
	Remark      string `json:"remark,optional"`
}

type AdminChangePasswordRequest struct {
	OldPassword     string `json:"old_password"`
	NewPassword     string `json:"new_password" validate:"min=6"`
	ConfirmPassword string `json:"confirm_password"`
}

type AdminLoginRequest struct {
	Account  string `json:"account" validate:"required"` // 邮箱/用户名/手机号
	Password string `json:"password" validate:"required"`
	IP       string `json:"ip,optional"`
}

type AdminLoginResponse struct {
	AccessToken  string        `json:"access_token"`
	RefreshToken string        `json:"refresh_token"`
	ExpiresIn    int64         `json:"expires_in"`
	User         AdminUserInfo `json:"user"`
}

type AdminUserIDRequest struct {
	ID int64 `path:"id"`
}

type AdminUserInfo struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Mobile    string `json:"mobile"`
	RealName  string `json:"real_name"`
	Avatar    string `json:"avatar"`
	Type      int    `json:"type"`
	TypeText  string `json:"type_text"`
	Status    int    `json:"status"`
	CreatedAt string `json:"created_at"`
}

type BatchUpdateSafetyStockReq struct {
	Items []SafetyStockItem `json:"items"`
}

type BrandDetailResp struct {
	ID               int64  `json:"id"`
	Name             string `json:"name"`
	Logo             string `json:"logo"`
	Description      string `json:"description"`
	Website          string `json:"website"`
	TrademarkNumber  string `json:"trademark_number"`
	TrademarkCountry string `json:"trademark_country"`
	EnablePage       bool   `json:"enable_page"`
	Sort             int    `json:"sort"`
	Status           int8   `json:"status"`
	ProductCount     int64  `json:"product_count"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

type BrandMarketItemResp struct {
	MarketID  int64 `json:"market_id"`
	IsVisible bool  `json:"is_visible"`
}

type BrandMarketVisibilityResp struct {
	BrandID int64                 `json:"brand_id"`
	Markets []BrandMarketItemResp `json:"markets"`
}

type CategoryDetailResp struct {
	ID             int64  `json:"id"`
	ParentID       int64  `json:"parent_id"`
	Name           string `json:"name"`
	Code           string `json:"code"`
	Level          int    `json:"level"`
	Sort           int    `json:"sort"`
	Icon           string `json:"icon"`
	Image          string `json:"image"`
	SeoTitle       string `json:"seo_title"`
	SeoDescription string `json:"seo_description"`
	Status         int8   `json:"status"`
	ProductCount   int64  `json:"product_count"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type CategoryMarketItemResp struct {
	MarketID  int64 `json:"market_id"`
	IsVisible bool  `json:"is_visible"`
}

type CategoryMarketVisibilityResp struct {
	CategoryID int64                    `json:"category_id"`
	Markets    []CategoryMarketItemResp `json:"markets"`
}

type CategorySortItem struct {
	ID   int64 `json:"id"`
	Sort int   `json:"sort"`
}

type CategoryTreeReq struct {
}

type CategoryTreeResp struct {
	ID             int64               `json:"id"`
	ParentID       int64               `json:"parent_id"`
	Name           string              `json:"name"`
	Code           string              `json:"code"`
	Level          int                 `json:"level"`
	Sort           int                 `json:"sort"`
	Icon           string              `json:"icon"`
	Image          string              `json:"image"`
	SeoTitle       string              `json:"seo_title"`
	SeoDescription string              `json:"seo_description"`
	Status         int8                `json:"status"`
	ProductCount   int64               `json:"product_count"`
	CreatedAt      string              `json:"created_at"`
	UpdatedAt      string              `json:"updated_at"`
	Children       []*CategoryTreeResp `json:"children"`
}

type CreateBrandReq struct {
	Name             string `json:"name"`
	Logo             string `json:"logo,optional"`
	Description      string `json:"description,optional"`
	Website          string `json:"website,optional"`
	TrademarkNumber  string `json:"trademark_number,optional"`
	TrademarkCountry string `json:"trademark_country,optional"`
	EnablePage       bool   `json:"enable_page,optional"`
	Sort             int    `json:"sort,optional"`
}

type CreateBrandResp struct {
	ID int64 `json:"id"`
}

type CreateCategoryReq struct {
	Name           string `json:"name"`
	ParentID       int64  `json:"parent_id,optional"`
	Code           string `json:"code,optional"`
	Icon           string `json:"icon,optional"`
	Image          string `json:"image,optional"`
	SeoTitle       string `json:"seo_title,optional"`
	SeoDescription string `json:"seo_description,optional"`
	Sort           int    `json:"sort,optional"`
}

type CreateCategoryResp struct {
	ID int64 `json:"id"`
}

type CreateMarketReq struct {
	Code            string    `json:"code"`     // US, UK, DE, FR, AU
	Name            string    `json:"name"`     // United States
	Currency        string    `json:"currency"` // USD, GBP, EUR, AUD
	DefaultLanguage string    `json:"default_language,optional"`
	Flag            string    `json:"flag,optional"`
	TaxRules        TaxConfig `json:"tax_rules,optional"`
}

type CreateProductReq struct {
	Name            string   `json:"name"`
	Description     string   `json:"description,optional"`
	Price           int64    `json:"price"`
	Currency        string   `json:"currency,optional"`
	CostPrice       int64    `json:"cost_price,optional"`
	CategoryID      int64    `json:"category_id"`
	SKU             string   `json:"sku,optional"`
	Brand           string   `json:"brand,optional"`
	Tags            []string `json:"tags,optional"`
	Images          []string `json:"images,optional"`
	IsMatrixProduct bool     `json:"is_matrix_product,optional"`
	HSCode          string   `json:"hs_code,optional"`
	COO             string   `json:"coo,optional"`
	Weight          string   `json:"weight,optional"`
	WeightUnit      string   `json:"weight_unit,optional"`
	Length          string   `json:"length,optional"`
	Width           string   `json:"width,optional"`
	Height          string   `json:"height,optional"`
	DangerousGoods  []string `json:"dangerous_goods,optional"`
}

type CreateProductResp struct {
	ID int64 `json:"id"`
}

type CreateWarehouseReq struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	Country   string `json:"country,optional"`
	Address   string `json:"address,optional"`
	IsDefault bool   `json:"is_default,optional"`
}

type CreateWarehouseResp struct {
	ID int64 `json:"id"`
}

type GetBrandMarketVisibilityReq struct {
	BrandID int64 `path:"id"`
}

type GetBrandProductCountReq struct {
	ID int64 `path:"id"`
}

type GetBrandProductCountResp struct {
	Count int64 `json:"count"`
}

type GetBrandReq struct {
	ID int64 `path:"id"`
}

type GetCategoryMarketVisibilityReq struct {
	CategoryID int64 `path:"id"`
}

type GetCategoryProductCountReq struct {
	ID int64 `path:"id"`
}

type GetCategoryProductCountResp struct {
	Count int64 `json:"count"`
}

type GetCategoryReq struct {
	ID int64 `path:"id"`
}

type GetInventoryLogsReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"page_size,default=20"`
	SKUCode   string `form:"sku_code,optional"`
	ProductID int64  `form:"product_id,optional"`
	Type      string `form:"type,optional"` // manual, order, return, adjustment
}

type GetLowStockSKUsReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type GetMarketReq struct {
	ID int64 `path:"id"`
}

type GetProductReq struct {
	ID int64 `path:"id"`
}

type GetSKUInventoryReq struct {
	SKUCode string `path:"sku_code"`
}

type GetUserRequest struct {
	ID int64 `path:"id"`
}

type GetUserResponse struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Status    int    `json:"status"`
	CreatedAt string `json:"created_at"`
}

type GetWarehouseReq struct {
	ID int64 `path:"id"`
}

type InventoryLogResp struct {
	ID             int64  `json:"id"`
	SKUCode        string `json:"sku_code"`
	ProductID      int64  `json:"product_id"`
	WarehouseID    int64  `json:"warehouse_id"`
	ChangeType     string `json:"change_type"`
	ChangeQuantity int    `json:"change_quantity"`
	BeforeStock    int    `json:"before_stock"`
	AfterStock     int    `json:"after_stock"`
	OrderNo        string `json:"order_no"`
	Remark         string `json:"remark"`
	OperatorID     int64  `json:"operator_id"`
	CreatedAt      string `json:"created_at"`
}

type ListAdminUsersRequest struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Keyword  string `form:"keyword,optional"`
	Type     int    `form:"type,optional"`      // 1=平台超管 2=商家管理员 3=商家子账号
	Status   int    `form:"status,optional"`    // 1=正常 2=禁用
	TenantID int64  `form:"tenant_id,optional"` // 平台超管可指定租户
}

type ListAdminUsersResponse struct {
	List     []*AdminUserInfo `json:"list"`
	Total    int64            `json:"total"`
	Page     int              `json:"page"`
	PageSize int              `json:"page_size"`
}

type ListBrandReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Name     string `form:"name,optional"`
	Status   int8   `form:"status,optional"`
}

type ListBrandResp struct {
	List  []BrandDetailResp `json:"list"`
	Total int64             `json:"total"`
}

type ListCategoryReq struct {
	ParentID int64 `form:"parent_id,optional"`
}

type ListCategoryResp struct {
	List []*CategoryDetailResp `json:"list"`
}

type ListInventoryLogsResp struct {
	List  []*InventoryLogResp `json:"list"`
	Total int64               `json:"total"`
}

type ListLowStockSKUsResp struct {
	List  []*LowStockSKUResp `json:"list"`
	Total int64              `json:"total"`
}

type ListMarketsResp struct {
	List  []*MarketResponse `json:"list"`
	Total int64             `json:"total"`
}

type ListProductMarketsReq struct {
	ProductID int64 `path:"id"`
}

type ListProductMarketsResp struct {
	List []*ProductMarketResp `json:"list"`
}

type ListProductReq struct {
	Name       string `form:"name,optional"`
	CategoryID int64  `form:"category_id,optional"`
	Status     string `form:"status,optional"`
	MinPrice   int64  `form:"min_price,optional"`
	MaxPrice   int64  `form:"max_price,optional"`
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"page_size,default=20"`
	MarketID   int64  `form:"market_id,optional"`
}

type ListProductResp struct {
	List     []*ProductDetailResp `json:"list"`
	Total    int64                `json:"total"`
	Page     int                  `json:"page"`
	PageSize int                  `json:"page_size"`
}

type ListUsersRequest struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Name     string `form:"name,optional"`
	Email    string `form:"email,optional"`
}

type ListUsersResponse struct {
	List     []*GetUserResponse `json:"list"`
	Total    int64              `json:"total"`
	Page     int                `json:"page"`
	PageSize int                `json:"page_size"`
}

type ListWarehouseReq struct {
}

type ListWarehouseResp struct {
	List []*WarehouseDetailResp `json:"list"`
}

type LowStockSKUResp struct {
	SKUCode        string `json:"sku_code"`
	ProductID      int64  `json:"product_id"`
	ProductName    string `json:"product_name"`
	AvailableStock int    `json:"available_stock"`
	SafetyStock    int    `json:"safety_stock"`
}

type MarketResponse struct {
	ID              int64     `json:"id"`
	Code            string    `json:"code"`
	Name            string    `json:"name"`
	Currency        string    `json:"currency"`
	DefaultLanguage string    `json:"default_language"`
	Flag            string    `json:"flag"`
	IsActive        bool      `json:"is_active"`
	IsDefault       bool      `json:"is_default"`
	TaxRules        TaxConfig `json:"tax_rules"`
	CreatedAt       string    `json:"created_at"`
	UpdatedAt       string    `json:"updated_at"`
}

type MoveCategoryReq struct {
	ID          int64 `path:"id"`
	NewParentID int64 `json:"new_parent_id"`
}

type ProductDetailResp struct {
	ID              int64               `json:"id"`
	Name            string              `json:"name"`
	Description     string              `json:"description"`
	Price           int64               `json:"price"`
	Currency        string              `json:"currency"`
	CostPrice       int64               `json:"cost_price"`
	Stock           int                 `json:"stock"`
	Status          string              `json:"status"`
	CategoryID      int64               `json:"category_id"`
	CreatedAt       string              `json:"created_at"`
	UpdatedAt       string              `json:"updated_at"`
	SKU             string              `json:"sku"`
	Brand           string              `json:"brand"`
	Tags            []string            `json:"tags"`
	Images          []string            `json:"images"`
	IsMatrixProduct bool                `json:"is_matrix_product"`
	HSCode          string              `json:"hs_code"`
	COO             string              `json:"coo"`
	Weight          string              `json:"weight"`
	WeightUnit      string              `json:"weight_unit"`
	Length          string              `json:"length"`
	Width           string              `json:"width"`
	Height          string              `json:"height"`
	DangerousGoods  []string            `json:"dangerous_goods"`
	Markets         []ProductMarketInfo `json:"markets,optional"`
}

type ProductMarketInfo struct {
	MarketID   int64  `json:"market_id"`
	MarketCode string `json:"market_code"`
	MarketName string `json:"market_name"`
	IsEnabled  bool   `json:"is_enabled"`
	Price      string `json:"price"`
	Currency   string `json:"currency"`
}

type ProductMarketResp struct {
	ID                  int64  `json:"id"`
	ProductID           int64  `json:"product_id"`
	MarketID            int64  `json:"market_id"`
	MarketCode          string `json:"market_code"`
	MarketName          string `json:"market_name"`
	IsEnabled           bool   `json:"is_enabled"`
	Price               string `json:"price"`
	CompareAtPrice      string `json:"compare_at_price,optional"`
	Currency            string `json:"currency"`
	StockAlertThreshold int    `json:"stock_alert_threshold"`
	PublishedAt         string `json:"published_at,optional"`
}

type PushToMarketReq struct {
	ProductID int64    `path:"id"`
	MarketIDs []int64  `json:"market_ids"`
	Prices    []string `json:"prices"` // Price per market, same order as market_ids
}

type PushToMarketResp struct {
	Success []int64 `json:"success"` // Market IDs successfully added
	Failed  []int64 `json:"failed"`  // Market IDs that failed
}

type PutOnSaleReq struct {
	ID int64 `path:"id"`
}

type RegisterTenantAdminRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Mobile   string `json:"mobile,optional"`
	RealName string `json:"real_name" validate:"required"`
	Password string `json:"password" validate:"required,min=6"`
	TenantID int64  `json:"tenant_id,optional"` // 默认为0，创建平台超管时使用
}

type RegisterTenantAdminResponse struct {
	AccessToken  string        `json:"access_token"`
	RefreshToken string        `json:"refresh_token"`
	ExpiresIn    int64         `json:"expires_in"`
	User         AdminUserInfo `json:"user"`
}

type RemoveFromMarketReq struct {
	ProductID int64 `path:"id"`
	MarketID  int64 `path:"market_id"`
}

type SKUInventoryResp struct {
	SKUCode        string                        `json:"sku_code"`
	ProductID      int64                         `json:"product_id"`
	TotalStock     int                           `json:"total_stock"`
	AvailableStock int                           `json:"available_stock"`
	LockedStock    int                           `json:"locked_stock"`
	SafetyStock    int                           `json:"safety_stock"`
	IsLowStock     bool                          `json:"is_low_stock"`
	Warehouses     []*WarehouseInventoryItemResp `json:"warehouses"`
}

type SafetyStockItem struct {
	SKUCode     string `json:"sku_code"`
	SafetyStock int    `json:"safety_stock"`
}

type SetBrandMarketVisibilityReq struct {
	BrandID   int64   `path:"id"`
	MarketIDs []int64 `json:"market_ids"`
	Visible   bool    `json:"visible"`
}

type SetCategoryMarketVisibilityReq struct {
	CategoryID int64   `path:"id"`
	MarketIDs  []int64 `json:"market_ids"`
	Visible    bool    `json:"visible"`
}

type SetDefaultWarehouseReq struct {
	ID int64 `path:"id"`
}

type TakeOffSaleReq struct {
	ID int64 `path:"id"`
}

type TaxConfig struct {
	VatRate     string `json:"vat_rate,optional"`
	GstRate     string `json:"gst_rate,optional"`
	IossEnabled bool   `json:"ioss_enabled,optional"`
	IncludeTax  bool   `json:"include_tax,optional"`
}

type ToggleBrandPageReq struct {
	ID      int64 `path:"id"`
	Enabled bool  `json:"enabled"`
}

type UpdateBrandReq struct {
	ID               int64  `path:"id"`
	Name             string `json:"name"`
	Logo             string `json:"logo,optional"`
	Description      string `json:"description,optional"`
	Website          string `json:"website,optional"`
	TrademarkNumber  string `json:"trademark_number,optional"`
	TrademarkCountry string `json:"trademark_country,optional"`
	EnablePage       bool   `json:"enable_page,optional"`
	Sort             int    `json:"sort,optional"`
}

type UpdateBrandStatusReq struct {
	ID     int64 `path:"id"`
	Status int8  `json:"status"` // 0=disabled, 1=enabled
}

type UpdateCategoryReq struct {
	ID             int64  `path:"id"`
	Name           string `json:"name"`
	Code           string `json:"code,optional"`
	Icon           string `json:"icon,optional"`
	Image          string `json:"image,optional"`
	SeoTitle       string `json:"seo_title,optional"`
	SeoDescription string `json:"seo_description,optional"`
	Sort           int    `json:"sort,optional"`
}

type UpdateCategorySortReq struct {
	Sorts []CategorySortItem `json:"sorts"`
}

type UpdateCategoryStatusReq struct {
	ID     int64 `path:"id"`
	Status int8  `json:"status"` // 0=disabled, 1=enabled
}

type UpdateMarketReq struct {
	ID        int64     `path:"id"`
	Name      string    `json:"name,optional"`
	IsActive  *bool     `json:"is_active,optional"`
	IsDefault *bool     `json:"is_default,optional"`
	TaxRules  TaxConfig `json:"tax_rules,optional"`
}

type UpdateProductMarketReq struct {
	ProductID           int64  `path:"id"`
	MarketID            int64  `path:"market_id"`
	IsEnabled           *bool  `json:"is_enabled,optional"`
	Price               string `json:"price,optional"`
	CompareAtPrice      string `json:"compare_at_price,optional"`
	StockAlertThreshold int    `json:"stock_alert_threshold,optional"`
}

type UpdateProductReq struct {
	ID              int64    `json:"id"`
	Name            string   `json:"name"`
	Description     string   `json:"description,optional"`
	Price           int64    `json:"price"`
	Currency        string   `json:"currency,optional"`
	CategoryID      int64    `json:"category_id"`
	SKU             string   `json:"sku,optional"`
	Brand           string   `json:"brand,optional"`
	Tags            []string `json:"tags,optional"`
	Images          []string `json:"images,optional"`
	IsMatrixProduct bool     `json:"is_matrix_product,optional"`
	HSCode          string   `json:"hs_code,optional"`
	COO             string   `json:"coo,optional"`
	Weight          string   `json:"weight,optional"`
	WeightUnit      string   `json:"weight_unit,optional"`
	Length          string   `json:"length,optional"`
	Width           string   `json:"width,optional"`
	Height          string   `json:"height,optional"`
	DangerousGoods  []string `json:"dangerous_goods,optional"`
}

type UpdateProfileRequest struct {
	UserID   int64  `json:"user_id"`
	RealName string `json:"real_name,optional"`
	Avatar   string `json:"avatar,optional"`
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
}

type UpdateSKUStockReq struct {
	SKUCode        string `json:"sku_code"`
	WarehouseID    int64  `json:"warehouse_id,optional"` // 0 = all warehouses
	AvailableStock int    `json:"available_stock"`
	Remark         string `json:"remark,optional"`
}

type UpdateStockReq struct {
	ID       int64 `path:"id"`
	Quantity int   `json:"quantity"`
}

type UpdateUserRequest struct {
	ID     int64  `path:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar,optional"`
}

type UpdateWarehouseReq struct {
	ID        int64  `path:"id"`
	Name      string `json:"name"`
	Country   string `json:"country,optional"`
	Address   string `json:"address,optional"`
	IsDefault bool   `json:"is_default,optional"`
}

type UpdateWarehouseStatusReq struct {
	ID     int64 `path:"id"`
	Status int8  `json:"status"` // 0=disabled, 1=enabled
}

type WarehouseDetailResp struct {
	ID        int64  `json:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	Country   string `json:"country"`
	Address   string `json:"address"`
	IsDefault bool   `json:"is_default"`
	Status    int8   `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type WarehouseInventoryItemResp struct {
	WarehouseID    int64  `json:"warehouse_id"`
	WarehouseName  string `json:"warehouse_name"`
	AvailableStock int    `json:"available_stock"`
	LockedStock    int    `json:"locked_stock"`
}
