// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminChangePasswordRequest struct {
	OldPassword     string `json:"old_password"`
	NewPassword     string `json:"new_password" validate:"min=6"`
	ConfirmPassword string `json:"confirm_password"`
}

type AdminLoginRequest struct {
	Account  string `json:"account" validate:"required"` // 邮箱/用户名/手机号
	Password string `json:"password" validate:"required"`
	IP       string `json:"ip,optional"`
}

type AdminLoginResponse struct {
	AccessToken  string        `json:"access_token"`
	RefreshToken string        `json:"refresh_token"`
	ExpiresIn    int64         `json:"expires_in"`
	User         AdminUserInfo `json:"user"`
}

type AdminUserIDRequest struct {
	ID int64 `path:"id"`
}

type AdminUserInfo struct {
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Mobile    string `json:"mobile"`
	RealName  string `json:"real_name"`
	Avatar    string `json:"avatar"`
	Type      int    `json:"type"`
	TypeText  string `json:"type_text"`
	Status    int    `json:"status"`
	CreatedAt string `json:"created_at"`
}

type CreateMarketReq struct {
	Code            string    `json:"code"`     // US, UK, DE, FR, AU
	Name            string    `json:"name"`     // United States
	Currency        string    `json:"currency"` // USD, GBP, EUR, AUD
	DefaultLanguage string    `json:"default_language,optional"`
	Flag            string    `json:"flag,optional"`
	TaxRules        TaxConfig `json:"tax_rules,optional"`
}

type CreateProductReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Price       int64  `json:"price"`
	Currency    string `json:"currency,optional"`
	CostPrice   int64  `json:"cost_price,optional"`
	CategoryID  int64  `json:"category_id"`
}

type CreateProductResp struct {
	ID int64 `json:"id"`
}

type GetMarketReq struct {
	ID int64 `path:"id"`
}

type GetProductReq struct {
	ID int64 `path:"id"`
}

type GetUserRequest struct {
	ID int64 `path:"id"`
}

type GetUserResponse struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Status    int    `json:"status"`
	CreatedAt string `json:"created_at"`
}

type ListAdminUsersRequest struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Keyword  string `form:"keyword,optional"`
	Type     int    `form:"type,optional"`      // 1=平台超管 2=商家管理员 3=商家子账号
	Status   int    `form:"status,optional"`    // 1=正常 2=禁用
	TenantID int64  `form:"tenant_id,optional"` // 平台超管可指定租户
}

type ListAdminUsersResponse struct {
	List     []*AdminUserInfo `json:"list"`
	Total    int64            `json:"total"`
	Page     int              `json:"page"`
	PageSize int              `json:"page_size"`
}

type ListMarketsResp struct {
	List  []*MarketResponse `json:"list"`
	Total int64             `json:"total"`
}

type ListProductReq struct {
	Name       string `form:"name,optional"`
	CategoryID int64  `form:"category_id,optional"`
	Status     string `form:"status,optional"`
	MinPrice   int64  `form:"min_price,optional"`
	MaxPrice   int64  `form:"max_price,optional"`
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"page_size,default=20"`
}

type ListProductResp struct {
	List     []*ProductDetailResp `json:"list"`
	Total    int64                `json:"total"`
	Page     int                  `json:"page"`
	PageSize int                  `json:"page_size"`
}

type ListUsersRequest struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Name     string `form:"name,optional"`
	Email    string `form:"email,optional"`
}

type ListUsersResponse struct {
	List     []*GetUserResponse `json:"list"`
	Total    int64              `json:"total"`
	Page     int                `json:"page"`
	PageSize int                `json:"page_size"`
}

type MarketResponse struct {
	ID              int64     `json:"id"`
	Code            string    `json:"code"`
	Name            string    `json:"name"`
	Currency        string    `json:"currency"`
	DefaultLanguage string    `json:"default_language"`
	Flag            string    `json:"flag"`
	IsActive        bool      `json:"is_active"`
	IsDefault       bool      `json:"is_default"`
	TaxRules        TaxConfig `json:"tax_rules"`
	CreatedAt       string    `json:"created_at"`
	UpdatedAt       string    `json:"updated_at"`
}

type ProductDetailResp struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
	Currency    string `json:"currency"`
	CostPrice   int64  `json:"cost_price"`
	Stock       int    `json:"stock"`
	Status      string `json:"status"`
	CategoryID  int64  `json:"category_id"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type PutOnSaleReq struct {
	ID int64 `path:"id"`
}

type RegisterTenantAdminRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Mobile   string `json:"mobile,optional"`
	RealName string `json:"real_name" validate:"required"`
	Password string `json:"password" validate:"required,min=6"`
	TenantID int64  `json:"tenant_id,optional"` // 默认为0，创建平台超管时使用
}

type RegisterTenantAdminResponse struct {
	AccessToken  string        `json:"access_token"`
	RefreshToken string        `json:"refresh_token"`
	ExpiresIn    int64         `json:"expires_in"`
	User         AdminUserInfo `json:"user"`
}

type TakeOffSaleReq struct {
	ID int64 `path:"id"`
}

type TaxConfig struct {
	VatRate     string `json:"vat_rate,optional"`
	GstRate     string `json:"gst_rate,optional"`
	IossEnabled bool   `json:"ioss_enabled,optional"`
	IncludeTax  bool   `json:"include_tax,optional"`
}

type UpdateMarketReq struct {
	ID       int64     `path:"id"`
	Name     string    `json:"name,optional"`
	IsActive *bool     `json:"is_active,optional"`
	TaxRules TaxConfig `json:"tax_rules,optional"`
}

type UpdateProductReq struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Price       int64  `json:"price"`
	Currency    string `json:"currency,optional"`
	CategoryID  int64  `json:"category_id"`
}

type UpdateProfileRequest struct {
	UserID   int64  `json:"user_id"`
	RealName string `json:"real_name,optional"`
	Avatar   string `json:"avatar,optional"`
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
}

type UpdateStockReq struct {
	ID       int64 `path:"id"`
	Quantity int   `json:"quantity"`
}

type UpdateUserRequest struct {
	ID     int64  `path:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar,optional"`
}
